### ISSUE TITLE
Cross compile to 2.12.0?

### ISSUE THREAD

**Issue by daviddenton** [velvia/msgpack4s#11]
Is there a plan to add support for the new Scala version? I don't mind submitting a PR to get it done (assuming it's not blocked), but would like to know that it would get released.

:)

**Comment by velvia** [comment]
If you submit a PR I’d be happy to release it.

**Comment by daviddenton** [comment]
As an FYI, it's currently blocked on play-json being released for 2.12.0.

**Comment by velvia** [comment]
:/   C’mon Play people!  :)
