### ISSUE TITLE
Compatibility with Scala 2.10

### ISSUE THREAD

**Issue by raycheung** [velvia/msgpack4s#14]
I'm new to Scala and I love this library --- it simply works neatly.

However for some other libraries I'm stuck with Scala 2.10, and currently msgpack4s is cross-compiled to only 2.11 and 2.12. How hard is it to support 2.10 as well? What should I do to achieve that?

Very much appreciated.

**Comment by velvia** [comment]
Hi Ray,

Hmmm, the 2.10 support was dropped just recently and the API hasn’t really changed.  Would you be able to go back a version or two?

**Comment by raycheung** [comment]
Thank you @velvia, I fallback to 0.5.2 and it's all good. :bowing_man:

**Comment by velvia** [comment]
Awesome!
