### ISSUE TITLE
Tuple[A, B]

### ISSUE THREAD

**Issue by dazebug** [velvia/msgpack4s#6]
Is there any option for tuples? or scheduled?

**Comment by velvia** [comment]
Not at the moment, but would not be hard to add.  Are you interested in adding a patch?  Would probably be faster but I’ll get to this at some point.

**Comment by dazebug** [comment]
Do you have any comments for these two ideas?

https://github.com/frograms/msgpack4s/commit/a9487f7f32b778334292d862946257e48bb13733
https://github.com/frograms/msgpack4s/commit/34db9f8e26730b70765aaed6b5a097fa9a9cf1e1

It will be very helpful

**Comment by velvia** [comment]
Hi, I think this is a great start!  Feel free to submit a PR (or let me know and I can just do it).
It would be nice to remove the boilerplate with macros, but we can do that later.

Thanks!

**Comment by andreaferretti** [comment]
Any news on this? It would be very useful, and it seems just a matter of adding @dazebug codecs

**Comment by velvia** [comment]
Sorry, haven’t had time to incorporate it.  If I have time this week I’ll try to put those ideas in there, but if you submit a PR that would help  :)

**Comment by dazebug** [comment]
Oh.. I'm little bit busy these days but if I have time, I'll try too..

**Comment by andreaferretti** [comment]
I went to [the source](https://github.com/frograms/msgpack4s) of this proposal and found everything already packaged together with tests and ready for inclusion. I am making a PR based on that, just in case, but it does not seem there is a lot of work needed

**Comment by velvia** [comment]
Thanks, looking forward to it!

**Comment by velvia** [comment]
This is now solved by #7
