### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by leonardehrenfried** [velvia/msgpack4s#9]
I know this is a bit complicated but I'd really appreciate if you'd deployed this to Maven Central.

I've done it a few times before and can help you with it.

**Comment by velvia** [comment]
Thanks, I'm just lazy about it because I need to get PGP signing working again.  Also will be out for two weeks.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
The jars are now published to JCentral, which at least from SBT doesn't require a special extra repo I think.

**Comment by aroberts** [comment]
JCenter is no longer enabled by default, and has performance problems for many users. Any chance of maven central?

**Comment by velvia** [comment]
Hi Andrew,

When you say it’s not enabled by default, you mean that in SBT you need some extra line to add it, is that right?
I haven’t had time to work on PGP packaging which is what is needed for maven central, let me see…

**Comment by aroberts** [comment]
Yep, there's the extra line that's needed. It would be no problem to just add the line, but I see way worse build times when fetching from jcentral.

**Comment by velvia** [comment]
Hmmm…  ok thanks for the feedback.  I’ll try to get GPG signing taken cared of if it helps improve everyones lives…. :-p

**Comment by leonardehrenfried** [comment]
Hey there,

I've helped getting another project onto Maven Central since opening this ticket and I've written an extensive guide on how to do it: https://github.com/iheartradio/ficus/pull/34

I also expanded this text a little and put it in a blog post: https://leonard.io/blog/2017/01/an-in-depth-guide-to-deploying-to-maven-central/

The good news is that the tooling became _way_ better from what when I last deployed to MC ~4 years ago. What was an hour of wading through confusing UIs is now ~10 minutes of plain sailing (if you are registered with Sonatype).

If it helps I'd be glad to open a PR with the necessary changes to `build.sbt` as I did to the ficus lib. The only thing you'd need to do would be to generate PGP keys and claim your group id on Sonatype.

**Comment by velvia** [comment]
Hi Leonard,

Thanks that would be very helpful actually. I already have a Sonatype account. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
"We can do no great things, just small things with great love." -mother Teresa

**Comment by velvia** [comment]
Thanks Leonard.
